"""채팅 첨부 파일 처리.

- 브라우저가 보낸 텍스트 파일(이름, 내용)을 검사하고 data/attachments/<대화 ID>/ 에 원본을 보관한다.
- ComfyUI 워크플로우 JSON이면 council_workflow 로 요약을 만든다.
- 모델 프롬프트에는 "요약 + 원본(길면 잘라서)"을, 대화 기록에는 요약만 남겨 다음 질문에서도 참고하게 한다.
"""
from __future__ import annotations

import re
import time
from pathlib import Path

from council_workflow import summarize_text

MAX_FILES = 5
MAX_FILE_CHARS = 2_000_000
RAW_PROMPT_BUDGET = 90_000      # 한 번의 프롬프트에 넣을 원본 최대 글자 수 (전체 첨부 합계)
HISTORY_SUMMARY_CHARS = 4_000   # 대화 기록에 남길 요약 길이
TEXT_EXT = {
    ".json", ".txt", ".md", ".py", ".yaml", ".yml", ".csv", ".tsv", ".toml", ".ini", ".cfg",
    ".log", ".js", ".ts", ".html", ".css", ".xml", ".ps1", ".bat", ".cmd", ".sh",
}
_BAD = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def safe_name(name: str) -> str:
    name = _BAD.sub("_", Path(str(name)).name).strip().rstrip(". ") or "file"
    return name[:120]


def validate(raw) -> list[dict]:
    if not raw:
        return []
    if not isinstance(raw, list):
        raise ValueError("첨부 형식이 올바르지 않습니다.")
    if len(raw) > MAX_FILES:
        raise ValueError(f"첨부는 한 번에 {MAX_FILES}개까지 가능합니다.")
    files = []
    for item in raw:
        if not isinstance(item, dict):
            raise ValueError("첨부 형식이 올바르지 않습니다.")
        name = safe_name(item.get("name", "file"))
        content = item.get("content", "")
        if not isinstance(content, str):
            raise ValueError(f"{name}: 텍스트 파일만 첨부할 수 있습니다.")
        if Path(name).suffix.lower() not in TEXT_EXT:
            raise ValueError(f"{name}: 지원하지 않는 형식입니다. (JSON·텍스트 계열만 가능)")
        if len(content) > MAX_FILE_CHARS:
            raise ValueError(f"{name}: 파일이 너무 큽니다 (최대 약 2MB).")
        files.append({"name": name, "content": content})
    return files


def process(files: list[dict], data_dir: Path, conversation_id: str) -> list[dict]:
    """원본 저장 + 요약. 반환 항목: name, size, kind, summary, path, content(프롬프트용, 기록에는 저장 안 함)"""
    out = []
    folder = Path(data_dir) / "attachments" / conversation_id
    stamp = time.strftime("%Y%m%d-%H%M%S")
    for f in files:
        summary = summarize_text(f["content"], f["name"]) if f["name"].lower().endswith(".json") else ""
        kind = "workflow" if summary else ("json" if f["name"].lower().endswith(".json") else "text")
        path = ""
        try:
            folder.mkdir(parents=True, exist_ok=True)
            target = folder / f"{stamp}_{f['name']}"
            n = 2
            while target.exists():
                target = folder / f"{stamp}_{n}_{f['name']}"
                n += 1
            target.write_text(f["content"], encoding="utf-8")
            path = str(target)
        except OSError:
            pass  # 보관 실패해도 이번 질문 분석은 진행
        out.append({"name": f["name"], "size": len(f["content"]), "kind": kind,
                    "summary": summary, "path": path, "content": f["content"]})
    return out


def prompt_block(items: list[dict]) -> str:
    if not items:
        return ""
    parts = ["## Attached files (the user attached these to the newest question)"]
    budget = RAW_PROMPT_BUDGET
    per_file = max(budget // len(items), 5_000)
    for it in items:
        parts.append(f"### File: {it['name']} ({it['size']:,} chars, {it['kind']})")
        if it["summary"]:
            parts.append("#### Parsed summary (generated by code from the JSON — reliable for node/model/color facts)\n"
                         + it["summary"])
        raw = it["content"]
        limit = min(per_file, budget)
        if len(raw) > limit:
            parts.append(f"#### Raw content (first {limit:,} of {len(raw):,} chars; rely on the parsed summary for the rest)\n"
                         f"```\n{raw[:limit]}\n```")
            budget -= limit
        else:
            parts.append(f"#### Raw content\n```\n{raw}\n```")
            budget -= len(raw)
    return "\n\n".join(parts) + "\n"


def history_records(items: list[dict]) -> list[dict]:
    """대화 기록(JSONL)에 남길 첨부 정보. 원본 내용은 넣지 않는다."""
    return [{
        "name": it["name"], "size": it["size"], "kind": it["kind"], "path": it["path"],
        "summary": it["summary"][:HISTORY_SUMMARY_CHARS] + ("…" if len(it["summary"]) > HISTORY_SUMMARY_CHARS else ""),
    } for it in items]
